---
abstract: 'Perl interface to libpng'
author:
  - 'Ben Bullock <bkb@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.44, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Image-PNG-Libpng
no_index:
  directory:
    - t
    - inc
    - tmpl
    - build
    - inc
  file:
    - t/IPNGLT.pm
requires:
  perl: '5.008001'
resources:
  bugtracker: https://github.com/benkasminbullock/image-png-libpng/issues
  repository: https://github.com/benkasminbullock/image-png-libpng
version: '0.57'
x_contributors:
  - 'Aaron Crane <arc@cpan.org>'
  - 'Greg Kennedy <gregk@cpan.org>'
  - 'Petr Pisar'
  - 'Phil Perry <pmperry@cpan.org>'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
